#!/bin/bash
#PBS -l ncpus=16
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -q bl2
#PBS -M ramifnu@iu.edu
#PBS -m abe
#PBS -o /bl2/ogce/workflow/scripts/filteringPETest/filteringPE.stdout
#PBS -e /bl2/ogce/workflow/scripts/filteringPETest/filteringPE.stderr

source /usr/share/modules/init/bash

module load bowtie/1.1.1
module load samtools/1.2.0

jobid=`echo $PBS_JOBID | cut -f 1 -d '.'`

left_input=SEQC_ILM_AGR_A_4_L08_AGTCAA_BD0J2JACXX_R1_Trimmed.fastq.gz
#left_input=/bl2/ogce/Data/ILM_AGR_SampleATrimmed/SEQC_ILM_AGR_A_4_L08_AGTCAA_BD0J2JACXX_R1_Trimmed.fastq.gz
right_input=SEQC_ILM_AGR_A_4_L08_AGTCAA_BD0J2JACXX_R2_Trimmed.fastq.gz
#right_input=/bl2/ogce/Data/ILM_AGR_SampleATrimmed/SEQC_ILM_AGR_A_4_L08_AGTCAA_BD0J2JACXX_R2_Trimmed.fastq.gz

export BOWTIE_INDEXES="/bl2/ogce/libraries/Testing-SEQC/src/fastaFiles"
#export BOWTIE_INDEXES="/bl2/ogce/workflow/scripts/filteringPETest/"
export LD_LIBRARY_PATH=/usr/local/packages/flexbar/2.2/:$LD_LIBRARY_PATH
export PATH=/usr/local/packages/flexbar/2.2/bin:$PATH

nthreads=3

cd /bl2/ogce/workflow/scripts/filteringPETest/

/bl2/ogce/libraries/Testing-SEQC/src/filteringPE/filteringPE.sh i1.8 16 $left_input $right_input
